#!/bin/bash
echo "📋 Проверка логов Vercel..."
echo ""
echo "Для проверки логов вручную:"
echo "1. Откройте: https://vercel.com/world-wide-services-62780b79/gpt-agent-kwid/logs"
echo "2. Выберите последний deployment"
echo "3. Ищите 'Error creating user' или 'Registration error'"
echo ""
echo "Или проверьте Runtime Logs:"
echo "https://vercel.com/world-wide-services-62780b79/gpt-agent-kwid/logs?environment=production"
