#!/bin/bash
# ФИНАЛЬНЫЕ ИНСТРУКЦИИ ПО НАСТРОЙКЕ ПРОДАКШЕНА

echo "🎉 ПРОДАКШЕН НАСТРОЕН! ОСТАЛИСЬ ФИНАЛЬНЫЕ ШАГИ"
echo "=============================================="
echo ""
echo "✅ Миграции выполнены успешно"
echo "✅ Все API ключи найдены"
echo "✅ База данных готова"
echo ""

echo "🔐 НУЖНО СДЕЛАТЬ ВРУЧНУЮ:"
echo "========================"
echo ""

echo "1. 🌐 Настройка Vercel Environment Variables:"
echo "   Перейдите: https://vercel.com/dashboard"
echo "   Выберите проект: gpt-agent-kwid"
echo "   Перейдите в Settings → Environment Variables"
echo ""
echo "   Добавьте эти переменные:"
echo ""
echo "   NEXTAUTH_SECRET=XH9mgmu70y7LaauJBoI7ynjGXlja6u4JCE894ZeKgKk="
echo "   NEXTAUTH_URL=https://gpt-agent-kwid-5rtehrrok-world-wide-services-62780b79.vercel.app"
echo "   SUPABASE_URL=https://rpzchsgutabxeabbnwas.supabase.co"
echo "   SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwemNoc2d1dGFieGVhYmJud2FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1NjMzMzgsImV4cCI6MjA3NTEzOTMzOH0.aDEY7EQQLf8kd-H4cOWJbFzalkG9pjHkhOo6pkVDlLI"
echo "   SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwemNoc2d1dGFieGVhYmJud2FzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTU2MzMzOCwiZXhwIjoyMDc1MTM5MzM4fQ.UIkX-rUGGTbMGfd5YoF41Dx3QBuLH13nO-R3BXdbx2I"
echo "   NEXT_PUBLIC_SUPABASE_URL=https://rpzchsgutabxeabbnwas.supabase.co"
echo "   NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwemNoc2d1dGFieGVhYmJud2FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1NjMzMzgsImV4cCI6MjA3NTEzOTMzOH0.aDEY7EQQLf8kd-H4cOWJbFzalkG9pjHkhOo6pkVDlLI"
echo "   OPENROUTER_API_KEY=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"
echo "   NODE_ENV=production"
echo "   DEMO_MODE=false"
echo "   E2E_ONBOARDING_FAKE=false"
echo ""

echo "2. 🔗 Настройка Supabase Authentication:"
echo "   Перейдите: https://supabase.com/dashboard/project/rpzchsgutabxeabbnwas/auth/settings"
echo "   В разделе 'Redirect URLs' добавьте:"
echo ""
echo "   https://gpt-agent-kwid-5rtehrrok-world-wide-services-62780b79.vercel.app/api/auth/callback/*"
echo "   https://gpt-agent-kwid-5rtehrrok-world-wide-services-62780b79.vercel.app/integrations/kommo/oauth/callback"
echo ""

echo "🎯 ПОСЛЕ ВЫПОЛНЕНИЯ ЭТИХ ШАГОВ:"
echo "================================"
echo ""
echo "🌟 Production URL: https://gpt-agent-kwid-5rtehrrok-world-wide-services-62780b79.vercel.app"
echo ""
echo "📋 Начните работу:"
echo "1. Перейдите на сайт"
echo "2. Зарегистрируйтесь (/register)"
echo "3. Создайте организацию"
echo "4. Настройте AI агентов (/manage/[org-id]/ai-agents)"
echo "5. Подключите CRM (/manage/[org-id]/integrations)"
echo ""

echo "🚀 ВАШ GPT AGENT PLATFORM ГОТОВ К ПРОДАКШЕНУ!"
echo ""
echo "🎊 ПОЗДРАВЛЯЕМ! ПРОЕКТ ЗАПУЩЕН!"
