#!/bin/bash
# Шаблон переменных окружения для production
# Скопируйте эти переменные в Vercel Dashboard или .env.production

echo "=== ПРОДАКШЕН ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ ==="
echo ""
echo "# === АУТЕНТИФИКАЦИЯ ==="
echo "NEXTAUTH_SECRET=XH9mgmu70y7LaauJBoI7ynjGXlja6u4JCE894ZeKgKk="
echo "NEXTAUTH_URL=https://gpt-agent-kwid-5rtehrrok-world-wide-services-62780b79.vercel.app"
echo ""
echo "# === SUPABASE БАЗА ДАННЫХ ==="
echo "# Получить реальные ключи из: https://supabase.com/dashboard/project/rpzchsgutabxeabbnwas/settings/api"
echo "SUPABASE_URL=https://rpzchsgutabxeabbnwas.supabase.co"
echo "SUPABASE_ANON_KEY=your_supabase_anon_key"
echo "SUPABASE_SERVICE_ROLE_KEY=your_supabase_service_role_key"
echo ""
echo "# === REDIS (опционально) ==="
echo "REDIS_URL=redis://username:password@your-redis-host:port"
echo "UPSTASH_REDIS_REST_URL=https://your-upstash-redis-url"
echo "UPSTASH_REDIS_REST_TOKEN=your_upstash_token"
echo ""
echo "# === AI API (OPENROUTER) ==="
echo "OPENROUTER_API_KEY=sk-or-v1-your-openrouter-api-key"
echo ""
echo "# === ПРОДАКШЕН НАСТРОЙКИ ==="
echo "NODE_ENV=production"
echo "DEMO_MODE=false"
echo "E2E_ONBOARDING_FAKE=false"
echo "SUPABASE_DEFAULT_ORGANIZATION_ID="
echo ""
echo "=== ИНСТРУКЦИИ ==="
echo "1. Перейдите в Supabase Dashboard: https://supabase.com/dashboard/project/rpzchsgutabxeabbnwas/settings/api"
echo "2. Скопируйте anon public и service_role secret ключи"
echo "3. Добавьте все переменные в Vercel Dashboard"
echo "4. Получите OPENROUTER_API_KEY с https://openrouter.ai/keys"
echo "5. Настройте Redis в Upstash (опционально)"
echo ""
echo "=== ДОПОЛНИТЕЛЬНЫЕ ШАГИ ==="
echo "1. Выполните SQL миграции в Supabase Dashboard -> SQL Editor:"
echo "   - supabase/schema.sql"
echo "   - supabase/migrations/*.sql"
echo "2. Создайте storage bucket: scripts/create-storage-bucket.sql"
echo "3. Настройте redirect URLs в Authentication -> Settings"
